### ISSUE TITLE
How can I use IBAnimatable on a custom subclass ?

### ISSUE THREAD

**Issue by leonardbonfils** [IBAnimatable/IBAnimatable#117]
I have text fields that are of class "KaedeTextField" (from [this GitHub library](https://github.com/raulriera/TextFieldEffects)). How can I still animate these text fields ?

**Comment by tbaranes** [comment]
You have to create a `KaedeTextField` subclass, then make it conforms the `IBAnimatable` protocols you need: `Animatable`, `DesignableGradient`... You can check out [`AnimatableView`](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/AnimatableView.swift) to have an example of an implementation of the protocols. This subview is conform to almost all protocols available. 

EDIT: May be a duplicate of #55

**Comment by JakeLin** [comment]
@tbaranes thanks for your great explanation. Because `IBAnimatable` uses protocol oriented approach to provide protocol extensions. It would not pollute the class hierarchy when we conform to those protocols, it is very easy to integrate with other great libraries. 

I will create a document how to integrate `IBAnimatable` with other libraries. It will be very similar to what @tbaranes said above. 

I got an idea about this, if we fork the original repo e.g. [KaedeTextField](https://github.com/raulriera/TextFieldEffects), [LTMorphingLabel](https://github.com/lexrus/LTMorphingLabel) or [Material](https://github.com/CosmicMind/Material) and integrate with `IBAnimatable` to make them IBDesingable and Animatable. Then set them as a sub spec of `IBAnimatable/Material` to provide a plugin system.

**Comment by tbaranes** [comment]
Great idea the document. It seems to be necessary since it's a regular case.
Don't you think the plugin system will be a lot of work and maintenance?

**Comment by JakeLin** [comment]
@tbaranes you are right, plugin is just an idea and not our main focus. I got the idea because of Swift protocol oriented paradigm, `IBAnimatable` is so flexible to extend. It probably can support plugin system like jQuery, plugins can be developed and maintained by any developer. I am not sure can we get to the far. But for now, we focus on the vision, and current one is transition animations. 

And other important part is the documentation, once we release version 2 (transition animations). I would like to start writing stuff like protocol oriented, protocol extensions, IBDesignable and IBInspectable, and try to promote the project as well.

**Comment by leonardbonfils** [comment]
Thank you very much, and sorry for replying a little late (I don't check GitHub that often...). I indeed created a custom subclass of KaedeTextField and implemented all the required IBAnimatable-related protocols and everything seems to work fine. Thanks.
