### ISSUE TITLE
More system transition animators (animation controllers)

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#126]
To have more system transition animations can be configured in Interface Builder.

Unlock all system built-in animations, We have `SystemCubeAnimator` and `SystemFlipAnimator` now, we can easily unlock all system built-in animations in [SystemTransitionType](https://github.com/JakeLin/IBAnimatable/blob/master/IBAnimatable/SystemTransitionType.swift). They all have same implementation with different parameters. Refer to http://iphonedevwiki.net/index.php/CATransition

Documents:
- [How to develop an animator (animation controller)](https://github.com/JakeLin/IBAnimatable/wiki/How-to-develop-an-animator-%28animation-controller%29)
- [How to develop an animator using system built in animation](https://github.com/JakeLin/IBAnimatable/wiki/How-to-develop-an-animator-using-system-built-in-animation)

**Comment by tbaranes** [comment]
If we already have all of them, it would be a huge work :laughing: 
Seems we are gonna have a lot of fun!

**Comment by JakeLin** [comment]
@tbaranes too good to be true if we can implement all of them. I think we can do frequent releases for every one or few animators. Once we have implemented some of popular transition animators, it is good enough to use in most of transitions.

**Comment by tbaranes** [comment]
Just to keep in mind: the animation `SystemPageCurl` could be refactored in order to use `animateWithCATransition`, in order words creating a new enums instead of using the enums. The result won't change but will create a breaking change, nevertheless, it will make sense.

Also, here the full list of the system animators and their implementation state:
- [x] Fade
- [x] MoveIn
- [x]  Push
- [x]  Reveal
- [x] Flip
- [x]  Cube
- [x]  PageCurl
- [x]  PageUnCurl
- [x]  RippleEffect
- [x]  SuckEffect
- [x]  CameraIris
- [x]  CameraIrisHollowOpen
- [x]  CameraIrisHollowClose
- [x]  Rotate

That list doesn't contains the private transition, source from [stackoverflow](http://stackoverflow.com/a/12593393/4177109)

**Comment by JakeLin** [comment]
Don't mind for the breaking changes for renaming `SystemPageCurl`, should follow the system names. :+1:  for the check list.

**Comment by tbaranes** [comment]
Should we renamed that issue `More system transition animators` and create a new one for the `custom transition animators`?

Once all the PR merged, we also may make a new released since all the system ones are implemented.
What do you think? :dancers:

**Comment by JakeLin** [comment]
@tbaranes agree, we can release 2.2 once once we merge all your PRs, good on you. 👍  

Have created a new issue for [Custom transition animators (animation controllers)](https://github.com/JakeLin/IBAnimatable/issues/155)

**Comment by tbaranes** [comment]
Don't you want review them? :open_mouth:
