### ISSUE TITLE
Separate the framework and the app to distinct repos 

### ISSUE THREAD

**Issue by seanwoodward** [IBAnimatable/IBAnimatable#151]
If the repos are distinct for framework and app, other projects that reference the framework won't drag all of the app code in the submodule. Can be done pretty easily and shouldn't break any existing projects. I have done this in a downstream clone and used Carthage to setup the submodule.

**Comment by JakeLin** [comment]
@seanwoodward thanks for your suggestion. The reason why we keep it as one repo because we want some one (maybe not good at iOS development) can download the repo and "CMD+R" to run and play around the demo app. Since we support CocoaPods or Carthage, they won't package the source code from `IBAnimatableApp` target. 

Also to shrink the repo, we did move all assets for the README.md to another repo https://github.com/JakeLin/IBAnimatable-Misc

Please let me know if you have any suggestions.

**Comment by seanwoodward** [comment]
@JakeLin first, thanks for coming up with such a great framework. I can't think of a project that would not benefit from its use. And that's why I think the separation is important. Package managers pull the entire repo for each reference (Carthage anyway), so the app storyboards, etc. get pulled along with it. A few releases ago, Carthage had trouble with the single Info.plist. Developers new to iOS would probably benefit more from learning to use dependent frameworks. Even if they chose not to use a package manager, a simple git statement get's them up and running with the example app.

My two cents, for what it's worth. I am grateful for the project and look forward to contributing when I can.

Cheers.

**Comment by tbaranes** [comment]
I don't really like the idea to separate the demo project, it's really useful to have just to clone a project, open the demo workspace, and run it to have a quick idea of how it's working. However, I understand what you are saying, that makes me asking how popular open source project such as `Alamofire` are handling that issue? 

I'm pretty sure that they are not using a separate repot for their demo project, as well as their unit tests even if they are supporting SPM, carthage... did we miss something?

**Comment by seanwoodward** [comment]
@tbaranes I have seen similar setups in other frameworks and thought it made sense here, and only, because it was easy to implement.

**Comment by JakeLin** [comment]
@seanwoodward  glad you like `IBAnimatable`. Can you please let us know which frameworks have similar setups if you find them? Are they UI frameworks? 

I agree with @tbaranes because one of my repo called SwiftWeather, it has quick detailed description https://github.com/JakeLin/SwiftWeather#how-to-build but I still occasionally receive requests for asking for help to build the project. `IBAnimatable` is not only a library for developers but also for designers, I have chatted with some designers before they do want some thing download and run. we may keep the demo app in the same repo now until we find better solution to handle the onboarding process.

**Comment by JakeLin** [comment]
Since we decided to keep the current project structure, we close this issue now. 

@seanwoodward please let me know if you have any questions or you'd like to provide more information on this, thanks.
