### ISSUE TITLE
Can we use animators with child view controllers?

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#188]
In my current app, I'd like to use the `Fold` animations when transitioning between two child view controllers. From what I know about the animators, I don't think we can. For example, for a fade transition, I will have the following code (approximately):

``` swift
        oldViewController.willMoveToParentViewController(nil)
        addChildViewController(newViewController)
        addSubview(newViewController.view, toView:self.containerView!)
        newViewController.view.alpha = 0
        newViewController.view.layoutIfNeeded()
        UIView.animateWithDuration(animationDuration, animations: {
            newViewController.view.alpha = 1
            oldViewController.view.alpha = 0
        }, completion: { finished in
            oldViewController.view.removeFromSuperview()
            oldViewController.removeFromParentViewController()
            newViewController.didMoveToParentViewController(self)
        })
```

But that's a bit sad to have to rewrite it since we already did it in `FadeAnimator`, or if I wanted to use a more complex transition... any suggestions about this?

That issue may be related to #187

**Comment by JakeLin** [comment]
@tbaranes Have you seen this article before, https://www.objc.io/issues/12-animations/custom-container-view-controller-transitions/ it looks like something similar to your requirements. Because all `***Animator`s conform to `UIViewControllerAnimatedTransitioning` it will work with the container ViewController uses `- (id <UIViewControllerAnimatedTransitioning>)containerViewController:(ContainerViewController *)containerViewController animationControllerForTransitionFromViewController:(UIViewController *)fromViewController toViewController:(UIViewController *)toViewController;`

**Comment by tbaranes** [comment]
Right, I'm gonna give a try. Thanks!

**Comment by tbaranes** [comment]
I finally get it working using your link, thanks to you. I will make a PR, I think it could be nice to have that feature in IBAnimatable.
