### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#193]
I'm creating this issue to track the discussion started in #186 

First thing, I think we have to decide what we want to keep in the main README:
- What is it?
- Install
- where to find the docs?
- Documentation (just a summary with the links)

As you suggested, we can move out all the API documentation, I think we have two solutions where we can move it:
- Creating a directory `Documentation` which will contains several markdown files, examples:
  - [Fastlane](https://github.com/fastlane/fastlane): 
  - [Quick](https://github.com/Quick/Quick)
  - [Moya](https://github.com/Moya/Moya)
  - [Alamofire](https://github.com/Alamofire/Alamofire) -> just the migration guide
- Put the documentation directly in the wiki

=> I prefer the first one since we already using the wiki with technical stuff. Moreover, it seems to be simpler to use

Whatever our final choice, here a first suggestion of how we can divide the API documentation:
- TransitionAnimatable.md
- Animatable.md
- Designable.md
- Extensions.md
- Segue.md -> should it be merged in TransitionAnimatable?

**Comment by JakeLin** [comment]
@tbaranes thanks for starting this, Do you like `Documentation` folder more than wiki? I don't mind either way.

I like your groups, may have some more friendly to the user thinking, they match the project's goal.
- Animations: Animatable
- UI: Designable
- Transitions: TransitionAnimatable and Segue
- Misc: Extensions  

Another important thing I am going to do after release 2.3 is blogging. I am going to write some blog posts about "How to prototype and App Store ready Apps in IB with IBAnimatable", "How to prototype and design animations in Swift Playground", "How to prototype and design transition animations in IB" etc. `IBAnimatable` is the first library to support designing transition animations in IB. I think it is a very useful tool for prototyping and design since we have a lot of comprehensive features.

**Comment by tbaranes** [comment]
Yes, I prefer the `Documentation` folder, I find it more usable since we can edit it them locally.

Excellent idea for your group names, it's user friendly and really understandable. 
I'm looking forward to read your articles, moreover it will be an excellent idea since `IBAnimatable` is more and more popular, but is clearly missing some tutorials / helpers to get started about advanced usage.

**Comment by tbaranes** [comment]
Closing it now since the new structure is already there. We can still open a new issues just to list the documentation missing.
