### ISSUE TITLE
API Improvement proposal - Supporting enum for Inspectable properties in code and Interface Builder 

### ISSUE THREAD

**Issue by lastMove** [IBAnimatable/IBAnimatable#218]
**enum checklist to improve**
- [x] MaskType
- [x] AnimationType
- [x] GradientStartPoint
- [x] BorderSide
- [x] BlurEffectStyle (Add new options `regular` and `prominent` for `UIBlurEffectStyle`)
- [x] ColorType - FlatColorsTypeScript.swift
- [x] GradientType - GradientsTypeScript.swift
- [x] InteractiveGestureType
- [x] TransitionAnimationType
- [x] TransitionFromDirection
- [x] TransitionHollowState
- [x] TransitionPageType
- [x] PresentationAnimationType
- [x] PresentationModalSize
- [x] PresentationModalPosition
- [x] PresentationKeyboardTranslation

Other tasks
- [x] Migration Guide 

-------- Original Message --------
Hi All, I really love using this library. However i think that the API can be improved.

Presently a lot of properties are String because of InterfaceBuilder. Some property would be more usable, self-documented and less error-prone if they were enums with associated type.

Enums with associatedType are powerful and fit perfectly with IBAnimatable Purpose.

Before pursuing one example with maskType.using enums it will be possible to make this:

``` Swift

animatableView.maskType = MaskType.Parrallelogram(angle:45, direction: .Top)

animatableView.maskType = .Polygon(sides:8)
animatableView.maskType = .Circle

animatableView.maskType = “Polygon(8)“ // yes this is possible since the MaskType Enum adopts StringLiteralConvertible protocol

BUT (sadly) this will NOT be possible 

let string = “Polygon(8);
animatableView.maskType = string // Since there is no StringConvertible protocol in swift (yet) , only String Lterals are convertible 

```

I tried a lot of thing to be able to do this AND to stay compatible with Interface Builder But No way :(

The most convenient way IMO is to make 2 properties. 

``` Swift

private var maskType : String
var eMaskType : MaskType

```

Since the string maskType is made for Interface Builder it can be private. 
The advantage is that when accessing from code they will be just one way exposed. 
and since MaskType is StringLiteralConvertible, the existant code that looks like : 
view.maskType = “Circle”

will justNeed to be transformed to 

`view.eMaskType = “Circle”
`
And we could use`@avalable(iOS, renamed=“eMaskType”)` in order to simplify the migration

However, Since WWDC is soon, we can just wait to see Interface Builder improvements :) 
I have already refactor maskType locally to an enum, for testing this. It works.

What do you think about it ?

**Comment by JakeLin** [comment]
@lastMove Thanks for your proposal, I like your ideas. We designed the APIs using `String` because the limitations and constraints of Xcode and Interface Builder. It should be fixed by Apple eventually (hopefully 😓). 

We have discussed this issue before in #50, I also push back the code to `wip/support-enum-for-non-ib-api` branch for your reference, please notice, the code is very outdated comparing with the current master. We didn't work out a good solution and decide to use String like `Polygon(8)`

For your solution, I have few of concerns.
0. Does it work if we set `maskType` as `private` like `private var maskType : String` in Interface Builder?
0. Will all APIs call use `maskType` has to move `eMaskType`? Breaking changes?

**Comment by lastMove** [comment]
Hi, 
I just read #50 a lot of good ideas, nice to read.

Yes private properties do work with InterfaceBuilder.
And yes it implies breaking changes. Either in InterfaceBuilder or in code API. 
Since we can use `@avalable(iOS, renamed=“eMaskType”)`
i think it easier to put those breaking changes in Code API

**Comment by JakeLin** [comment]
@lastMove if we have to introduce breaking changes. I rather do it in code, not in Interface Builder, but need to think about it carefully. Also, we do that, and we may be able to change all similar APIs together, e.g. `animationType`,  `maskType`... Because it is better to have all breaking changes in one release. Let's hope if Apple fixes this issue in WWDC, and see any better option we have.

**Comment by tbaranes** [comment]
I really like @lastMove improvements suggestion, it would be a great move since that minimise a lot of potential errors when using IBAnimatable programatically. 

I just have one suggestion: shouldn't we bring that changes in the same release as swift 3 support (#221). Since swift 3 is already huge breaking changes, it will be almost transparent.

**Comment by JakeLin** [comment]
@tbaranes good call, how about we focus on API improvements for version 3. Since we need to support Swift 3 new API guidelines. We can include @lastMove 's suggestions within that as well.

**Comment by lastMove** [comment]
To synthetize : 
- Naming : To stay compatible with Interface Builder we keep actual properties but they become _private_ and new enums public properties. 
  This

``` Swift
  // MARK: - MaskDesignable
@IBInspectable public var maskType: String? {
    didSet {
      configMask()
      configBorder()
    }
  }
```

 will become something like this : 

``` Swift
  // MARK: - MaskDesignable
  @IBInspectable private var maskType: String? {
    didSet {
      eMaskType = MaskType(string:maskType);
    }
  }
  public var eMaskType: MaskType? {
    didSet {
      configMask()
      configBorder()
    }
  }
```

Add the new Enum for instance MaskType can looks like this 👍 
https://gist.github.com/lastMove/e155d8aabe4aca9a792b5486fb2d87cf

Is that your vision ?

**Comment by JakeLin** [comment]
@lastMove thanks for your update, I like architecture very much 👍. And I have a few of questions about the implementation.
1. If we set `maskType` as `private`, will be any problem when the developer tries to subclass `AnimatableView`? I don't recommend subclassing from `AnimatableView`. Because if we want to have further customization for the UI elements, we should conform to protocols e.g. `MaskDesignable` directly to the custom UI element. That's how Protocol oriented programming works. But we can forbid someone from subclassing from `AnimatableView`. If someone does that, will it be a problem we set `maskType` as `private`?
2. Because IBAnimatble encourages the developer to use protocols to their own custom UI elements. We try to encapsulate as much as logic in Protocol Extension. And let the user use them concisely. We may be able to  put `eMaskType = MaskType(string:maskType);` within a Protocol Extension method.
3. Shall we always have failable `init` for `MaskType`, because the code in https://gist.github.com/lastMove/e155d8aabe4aca9a792b5486fb2d87cf#file-masktype-swift-L58 may crash the app.
4. Would you like to take the initiative for this change? We have discussed that before, Version 3 will focus on changing all APIs, it would be good to include this change in Version 3. If we all agree with that, we need to work on https://github.com/JakeLin/IBAnimatable/tree/swift3 branch for this change. 

please let me know if you have any questions, thanks again.

**Comment by lastMove** [comment]
@1 - Good point, since Swift doesn’t supports protected properties we have to make them private.

From code it’s not annoying for subclasses since they still have access to eMaskType. 
From Interface Builder I made some tests this may surprise you (I was very surprised) but privates properties of parent class still appear in IB. 
Here is how i test it : 
I made the maskType:String property private and subclass AnimatableView 

``` Swift
public class AnimatableViewChild : AnimatableView {
  @IBInspectable public var aaaaa:String?
}
```

![screen shot 2016-06-23 at 21 22 43](https://cloud.githubusercontent.com/assets/4633817/16323033/ef07c0e8-39a7-11e6-8fc2-ccc024d92d1a.png)

Very good news.

2 - Yes it would be great but  since we can’t declare private properties within protocol it can be complicated. Have you an idea for this ? 

3 - Yes it better to make initialiser failable but in this case i was conforming to StringLiteralConvertible which require a non-failable. although I don’t know if it really useful to conform to StringLiteralConvertible.

4 - Yes i will be happy to help with this, starting from monday i will have more time.

**Comment by JakeLin** [comment]
@lastMove 
1. what a surprise 😱  "privates properties of parent class still appear in IB"
2. No idea, need to be public in protocol
3. my opt out `StringLiteralConvertible` first? add back if needed.
4. Cool, thanks

**Comment by JakeLin** [comment]
@lastMove I have an idea for `extension MaskType : StringLiteralConvertible`, can we have an option for `MaskType` as `.none`, then if we can't convert the string to `MaskType`, we set it to `.none`. And we can guard it in `configMask`. How do you think?

**Comment by lastMove** [comment]
Yeah, good idea ! 
Will do that. 
Here is a list of "Enumable" properties : 
That i found in IBAnimatable :
borderSide
maskType
BlurEffectStyle

 What to add to it. 
Also It can be useful to create an IBEnum protocol. 
there is one "bug" in swift 2 that avoid protocol extension for Enum 
for instance it's not possible to do that : 

``` Swift

public protocol IBStringConvertible  {
  init?(string:String)
}
public extension IBStringConvertible where Self: MaskType {
}

```

because : Type 'Self' constrained to non-protocol type 'MaskType'. 

I have to try it with Xcode 8.

**Comment by tbaranes** [comment]
Here some more "enumable properties to complete the list:
- AnimationType
- GradientStartPoint

- GradientType
- SystemTransitionType
- TransitionAnimationType
- TransitionFromDirection
- TransitionHollowState
- TransitionPageType

**Comment by tbaranes** [comment]
Here a full list of all the enums used as designable properties:
- Designable enums (fair enough for a first version of this new API I suppose), that's includes the ones you already find:
  - AnimationType
  - GradientStartPoint
  - BorderSide
  - MaskType
  -  BlurEffectStyle
- Enums generated from scripts (if you change the enum, you also have to change the script):
  - ColorType
  - GradientType
- Transitions animations:
  - InteractiveGestureType
  - SystemTransitionType
  - TransitionAnimationType
  - TransitionFromDirection
  - TransitionHollowState
  - TransitionPageType

I think that's all the enums we currently have in IBAnimatable. Hope that I didn't miss one 😅
Anyway, I'm following that thread from far, but I'm really excited to see the result, that's gonna be awesome 👍 

If you need help once we decided about the final implementation, just ask! I will be glad to help since there a lot to convert.

**Comment by JakeLin** [comment]
For `ColorType` and `GradientType`, we can use `#colorLiteral` then we can preview the color in Xcode 8. It is very cool.

<img width="1112" alt="screen shot 2016-06-27 at 1 41 17 pm" src="https://cloud.githubusercontent.com/assets/573856/16367989/c6c96920-3c6c-11e6-99b7-f2557c011bd6.png">

**Comment by lastMove** [comment]
ty for this lit @tbaranes 
I started working on this. 
Unfortunately It's impossible (without some ugly tricks) to make protocol extension for Enum.
I tried two different implementations : 
A simpler one
https://gist.github.com/lastMove/8cda639fe29a4db52ff03201890860d9
And one without literal strings 
https://gist.github.com/lastMove/5be7046d40f6ac0b92d2373ccdb41c5f

I wanted to remove literal strings from the code but the only way i found add some implementations complications and ugliness ^^ 
What do you think about them ? 

and for ColorType : 

``` Swift
public extension ColorType
  var uicolor:UIColor {
    switch self {
    case .FlatEmerland:
      return #colorLiteral(red: 46 / 255, green:  204 / 255, blue:  113 / 255, alpha: 1.0)
    case .FlatPomegranate:
      return #colorLiteral(red: 192 / 255, green:  57 / 255, blue:  43 / 255, alpha: 1.0)
    case .FlatWetAsphalt:
      return #colorLiteral(red: 52 / 255, green:  73 / 255, blue:  94 / 255, alpha: 1.0)
    case .FlatTurquoise:
      return #colorLiteral(red: 26 / 255, green:  188 / 255, blue:  156 / 255, alpha: 1.0)
    case .FlatConcrete:
      return #colorLiteral(red: 149 / 255, green:  165 / 255, blue:  166 / 255, alpha: 1.0)
    case .FlatOrange:
      return #colorLiteral(red: 243 / 255, green:  156 / 255, blue:  18 / 255, alpha: 1.0)
 ... 
} 
}
```

By adding this computed property  these colors can be used from code.
I am trying to have a good "prototype" so don't hesitate to leave some comments even for details.

**Comment by JakeLin** [comment]
@lastMove I like the "Simpler implementation" version. https://gist.github.com/lastMove/8cda639fe29a4db52ff03201890860d9#file-masktype-swift-L62

The requirement is to add an extension method to Swift enum, but we can't. Then we create `IBEnum` to add `extractNameAndParams` extension method. I like this idea 👍

I also like your idea to put the conversion of `ColorType` inside the `enum ColorType` instead of `predefinedColorFromString` in `FillDesignable`.

Do you want to have access to push to the IBAnimatable repo? If so, you can push to some branches, and we can work together more efficiently. I think this will be a significant change, I can't think of every aspect upfront, we may need to keep improving it when we work on more enum types.  But your "prototype" is very good start with.

**Comment by lastMove** [comment]
Nice, 
Will we work on this in the swift3 branch or a new one.
Yes, It will simplify the process if i could push to this branch.

**Comment by JakeLin** [comment]
@lastMove I have added @tbaranes checklist to the top of your post. How about we work on them one by one and Pull Request to swfit3 branch? We can easily review them and discuss the changes. The order of the list doesn't matter. Some of the small enums we may be able to do them together in one PR. Once Xcode 8 GM releases, we can merge swift3 in master.  

BTW: you should receive the invite to be a collaborator of the project. Thanks for involving to this project, let's have some fun together 👯

**Comment by lastMove** [comment]
Thank you for this. 
Yep, it's better to work on them in separated branches. 
I will start with MaskType so.

**Comment by JakeLin** [comment]
@lastMove, thanks, please give me a buzz any time when you have any question, we can always push to a WIP branch for discussion.

**Comment by JakeLin** [comment]
I think we can remove `x` and `y` for `AnimationType` because we can use a better enum to support parameters. and use String MoveTo(50,150) for move to x:50 and y:150

Please let me know if you have any idea, thanks.

**Comment by lastMove** [comment]
Yep it's improve the coherence.
Could you delete the "wip/swift3-enum-masktype"
I have made a commit to "swift3-masktype"
Do you have some comments. 
Ideally i would like to put eMaskType to a MaskDesignable protocol extension.
 (it would prevents a lot of repetition code).
  Since a protocol cannot contains stored properties the only way is to use objective C associated properties. 
I don't know if it's a good idea.

**Comment by JakeLin** [comment]
@lastMove "wip/swift3-enum-masktype" has been deleted. You can delete any branch if you feel necessary, of cause, not master 😁, I will have a look at your commit and comment there, thanks.

**Comment by JakeLin** [comment]
@lastMove I have rebased swift3 branch to your branch "swift3-masktype" and made some changes based on my comments. We can test all masks in the demo app now, please have a look at #234. 

Because I don't know whether do you have any changes to your branch, I pushed all changes to new branch [feature/swift3-masktype](https://github.com/JakeLin/IBAnimatable/tree/feature/swift3-masktype)

You can also see the changes in the commits or here https://github.com/JakeLin/IBAnimatable/compare/swift3...feature/swift3-masktype?expand=1

It is not completed yet. Please feel free to give me any feedback because we are still trying to find out a good "prototype", thanks.

**Comment by lastMove** [comment]
Ok perfect, Your changes are good for me since it reduces the number of checks required. 
I will switch to your new branch, and test if everything works.

**Comment by JakeLin** [comment]
@lastMove great. Because the demo is an example for the users how to use the marks correctly, there are some edge cases not in the demo app. e.g. wrong data like Wave(0,10,45), or missing parameters like Wave(up,20). They should fall back to default parameters.

We can eailiy put the incorrect settings in IB and test them. There may be some edge cases I haven't thought, we may find out when we work on it more. Please let me know if you have any questions.

**Comment by lastMove** [comment]
@JakeLin Ok. I just found a crash with the new implementation, when there is less than 3 parameters to wave Mask (again ^^). 
I used to make a array extension to handle this :

``` Swift
internal extension CollectionType {
    /// Returns the element at the specified index iff it is within bounds, otherwise nil.
    subscript (safe index: Index) -> Generator.Element? {
        return indices.contains(index) ? self[index] : nil
    }
} 
// Usage
let width = params[safe:2]
```

I would like to create a utils file where we can put this kind of code.
If developers include IBAnimatable directly by copy-pasting the IBAnimatable folder, it could conflicts with another implementation. 
IMO it's it not a big problem. 
@JakeLin @tbaranes what do you think ?

**Comment by JakeLin** [comment]
@lastMove I think it OK because we recommend the user use IBAnimatable using package management tools like CocoaPods, Carthage or SPM. Even the user copy-paste the folder, they still need to use `params[safe:2]` to use it, it won't pollute any existing APIs.

**Comment by JakeLin** [comment]
@lastMove I found out an issue. When we use private for `maskType` like `@IBInspectable private var maskType: String?`. But we can preview the design in Interface Builder. We can fix it by changing it to `internal` like `@IBInspectable var maskType: String?`.

**Comment by lastMove** [comment]
Hum, annoying, good fix. 
I applied your fix, and fix the crash too. 
Now everything seems working.

**Comment by lastMove** [comment]
There was also a crash when polygon sides < 2. 
I made the minimum sides number to 3 to avoid this kind of problem. 
let polygonPath = maskPolygonBezierPath(max(sides, 3))

**Comment by JakeLin** [comment]
@lastMove Good on you for finding edge cases. I have an idea to use using something like

```
  // MARK: - MaskDesignable
  public var maskType: MaskType = .none {
    didSet {
      configMask()
      configBorder()
    }
  }

  @IBInspectable var _maskType: String? {
    didSet {
      maskType = MaskType(string: _maskType)
    }
  }
```

I will push a commit and let you help me review it.

**Comment by lastMove** [comment]
Actually I prefer this naming too.
But it breaks the retro-compatibility with existing storyboards.

**Comment by JakeLin** [comment]
@lastMove You're right, it will break the backward compatibility, we have to do some like adding a underscore `_` in runtime attributes for `_maskType`. 
<img width="493" alt="screen shot 2016-07-04 at 10 48 57 pm" src="https://cloud.githubusercontent.com/assets/573856/16561057/702cb314-423a-11e6-9e07-d8d9e8dd86ce.png">

But I am still tempted to change it. But I need you guys opinions. 
<img width="654" alt="screen shot 2016-07-04 at 10 40 21 pm" src="https://cloud.githubusercontent.com/assets/573856/16561223/58c22ab4-423b-11e6-87c8-1e8c53748dcd.png">

Since `_maskType` is `internal`, the user can't see it if they use package management tools. And they still see `Mask Type` in Interface Builder as above. It makes like Interface Builder can support Swift `enum`.

Here is the commit for that change:  https://github.com/JakeLin/IBAnimatable/commit/bb2a86e418facfbc2cdaedfa262c61d329555ef6

@lastMove @tbaranes please let me know your ideas, thanks.

**Comment by lastMove** [comment]
Hum, Interesting. 
For me In absolute terms it's better to have _maskType:String and maskType:MaskType. 
The only inconvenient is the Backward compatibility. But IMO we should do it, since more we wait more it will become difficult and hassling for users to have breaking changes.

We will have to write a migration guide. We could, maybe, write a shell-script that will automatically do the transition for current users (with a regex in all .storyboard files).

**Comment by tbaranes** [comment]
I'm really not a huge fan of interface builder breaking changes, but if it's necessary with a good documentation, it should be smooth enough. Moreover, if we have to break it, let's do it with swift 3 since it's already breaking everything!

**Comment by JakeLin** [comment]
Cool, let's change it. Interface Builder will display some warnings if we don't add the underscore. That can help the user notice the changes. 

Also as you guys said we should have a migration guild with some detailed images to show how to change them manually. Or change them using an editor with "replace all" for the storyboard file. Or even provide a script to that that. 

I'm so excited to improve IBAnimatble to a new degree.

**Comment by lastMove** [comment]
Nice !
So we can consider MaskType (and so the prototype) OK ?

**Comment by JakeLin** [comment]
Yes, I think it is very good. Shall we PR it to swift3? May add some comment/documentation for it as well.

**Comment by lastMove** [comment]
I added a little bit of documentation for MaskType. 
Since I am not a native english speaker, there is certainly some typos. Feel free to fix it ;)

**Comment by JakeLin** [comment]
@lastMove Cool, I like it, I think we are ready to bring it back to swift3 now. Would you like to submit a PR or can I do it?

**Comment by lastMove** [comment]
Hi all,
I started working on AnimationType. It's pretty straightforward now.
Everything seems to work from code. 
But when using it in storyboard it can be painful since it's case-sensitive. 
for example "squeezein" will not work. 
So I will try (I don't know how yet) to make it case-insensitive.

**Comment by JakeLin** [comment]
@lastMove thanks for picking up `AnimationType`. I think we should support case-insensitive, good idea 👍

I thought we could do it better by simplifying the enum with parameters. Because before we didn't find a good way to support Swift enum, we use `slideInLeft`, `slideInRight` and so on. But now we have a good way to support Swift enum with `IBEnum`. 

Can we use something like `case slideIn(from direction: AnimationDirection)` to simplify  `AnimationType`. We did something similar in `TransitionAnimationType` already (need some change for Swift 3 though). The difference is we used `fromDirection:` in `TransitionAnimationType` but `from direction:` should be more Swift 3. Please let me know how do you think, also let me know if you need any help. Thanks again.

**Comment by lastMove** [comment]
Oh Yes I see. Nice, It will simplify a lot the enum. 
Maybe something like this : 

``` Swift
public enum AnimationType {
  case slide(slideIn:Bool, direction:Direction)
  case squeeze(squeezeIn:Bool, direction:Direction)
  case fade(fadeIn:Bool, direction:Direction)
  case squeezeFade(squeezFadeIn:Bool, Direction:Direction)
  case zoom(zoomIn:Bool)
  case shake
  case pop
  case flip(axis:Axis)
  case morph
  case flash
  case wobble
  case swing
  case rotate(clockwise:Bool)
  case moveTo
  case moveBy
  case none

  public enum Axis {
    case x, y
  }
  public enum Direction {
    case left, right, up, down
  }
}
```

**Comment by lastMove** [comment]
This model Seems better : 

```
public enum AnimationType {
  case slide(way:Way, from:Direction)
  case squeeze(way:Way, from:Direction)
  case fade(way:Way, from:Direction)
  case squeezeFade(way:Way, from:Direction)
  case zoom(way:Way)
  case shake
  case pop
  case flip(along:Axis)
  case morph
  case flash
  case wobble
  case swing
  case rotate(clockwise:Bool)
  case moveTo
  case moveBy
  case none

  public enum Way {
    case Out, In
  }
  public enum Axis {
    case x, y
  }
  public enum Direction {
    case left, right, up, down
  }
}
```

I don't know how to  name the `Way` enum, I don't really like "Way"
Any Idea.

**Comment by JakeLin** [comment]
@lastMove I like the last one, it provides excellent readability for Interface Builder. e.g. `slide(in,left)`, `squeeze(out,up)`

I have little concern for that when you use this enum in code, as you said the name of "Way" is one, I don't know how to make it better 😅. But the concept of Way is great 👍. And the second parameter `from` might not be correct in some cases. e.g. `let sideOutToRight = AnimationType(Way.out, from: Direction.Right)`, it is not `from` in that case. May just use `case slide(way:Way, direction:Direction)`? 

Another one is we should be able to remove `x`, and `y` properties and put them as parameters of `moveTo` and `moveBy`. I don't like those two properties when I introduced them from day one. They are only used in two animation types `moveTo` and `moveBy`. Since we have better enum support, those properties can be removed now 😁

**Comment by lastMove** [comment]
@JakeLin  @tbaranes I was thinking that reworking AnimationType would be as easy as conforming to IBEnum ... I was wrong ;) 
Following JakeLin recommandations I ended up with something I like. (The counter part are the breaking changes ...). 

AnimationType is now like that : 

``` Swift
public enum AnimationType {
  case slide(way:Way?, direction:Direction?)
  case squeeze(way:Way?, direction:Direction?) // miss squeeze
  case fade(way:Way?, direction:Direction?) // miss fadeinout, fadeountin
  case squeezeFade(way:Way?, direction:Direction?)
  case zoom(way:Way?)
  case shake
  case pop
  case flip(along:Axis?)
  case morph
  case flash
  case wobble
  case swing
  case rotate(direction:RotationDirection?)
  case moveTo(x:Double?, y:Double?)
  case moveBy(x:Double?, y:Double?)
  case none

```

So I have [reworked Animatable.swift](https://github.com/JakeLin/IBAnimatable/commit/26dc6516a673c1550df5780752f7eeee77c0cc93?diff=split) 
Since it's a core part of IBAnimatable, it would be nice if you could both see and comment the code. 
one notable point : 
`view.squeezeInUp()` become `view.animate(.squeeze(.in, .up))`. 

Also since Playground is not working on my side, I made a Animations section in the Demo App.
To access it : 
![simulator screen shot 13 jul 2016 15 25 32](https://cloud.githubusercontent.com/assets/4633817/16805087/f8816ebe-490e-11e6-96da-b17481790fc1.png)
Forgot password => Animations. 
It's a picker where we can choose the animations to launch and see immediately the result. 
There is 2 squares, one using the new system and the other, the old one..
We can see the result of both and compare ; the goal is to have exactly the same behavior. 
There is still some differences but I wanted to show you both the code and results. 
Let me know if the changes are Ok or can be improved or whatever ;)

**Comment by tbaranes** [comment]
Really nice work on the example! A good first step for #238.

About the commit, I really like the output. The code is easier to read, and more concise. 

Here two feedbacks about the commit you linked:
- `case .squeeze(let way, let direction):` -> `case let .squeeze(way, direction):`. I know we are not following a particular convention, but I prefer the second switch syntax. It's easier to read  and understand the switch with a quick look
- Using enums are really useful, but can make the code harder to read if we abuse of switch. A nice way to handle this could be a mix between the old methods (`animateInWithX`, ...), and the new ones. For example, when an animation has a `direction`, just create a generic function that returns a tuple with all the values calculable from a direction (distance, and scale)

Good step on this @lastMove :+1:

**Comment by lastMove** [comment]
Thank you for your feedback.

Strangely I didn't know about this syntax, it effectively better, thanks I will use it.

I am agree, there are some repetitive code in the implementation. Could you provide me an example of what you mean ?

**Comment by tbaranes** [comment]
I was thinking something like that:

A function which return the right values following a direction:

``` swift
  func values(from direction: AnimationType.Direction, distance: (CGFloat, CGFloat), scale: (CGFloat, CGFloat) = (0, 0)) -> (CGFloat, CGFloat) {
    switch direction {
    case .left:
      return (-distance.0, scale.0)
    case .right:
      return (-distance.0, scale.0)
    case .down:
      return (-distance.1, scale.1)
    case .up:
      return (distance.1, scale.1)
    }
  }
```

Then the squeeze becomes:

```
  public func squeeze( way: AnimationType.Way, direction: AnimationType.Direction, completion: AnimatableCompletion? = nil) {
    let yDistance = screenSize.height * force
    let xDistance = screenSize.width * force
    let scale = 3 * force
    let values = values(from: direction, distance: (xDistance, yDistance), scale: (scale, scale))
    switch way {
    case .In:
      animateIn(values.0, values.1, values.2, values.3, 1, completion)
    case .Out where direction.isVertical():
      animateOut(values.0, values.1, values.2, values.3, 1, completion)
    case .Out:
      animateOut(values.0, values.1, values.2, values.3, 1, completion)
    }
  }
```

That's what I was thinking about. Using this will avoid to have 4-5 switch just to calculates a distance and scale from a direction. There probably a way to make it even better by improving the tuples usage with typealias, or whatever, maybe even creating two functions: one for the distance, one for the scale. Anyway, that's just the global idea, I didn't test it though, I'm not even sure that would work for every cases 😆

**Comment by JakeLin** [comment]
Very nice work @lastMove you have made a huge step to improve the demo app. And your API design makes the APIs much cleaner. 

@tbaranes 's implementation is great too. One thing I hate about is the `Animatable.swift` file is **toooooo big** and I wanted to but didn't find a way to simplify it. You guys solution is making that happen. 

I have a concern, should we make all parameters within the enum to **non-optional**? like 

``` Swift
public enum AnimationType {
  case slide(way:Way, direction:Direction)
  case flip(along:Axis)
  case morph
  case rotate(direction:RotationDirection)
  case moveTo(x:Double, y:Double)
  case none
```

If the user uses the API and they should provide a value to the enum, if we provide a documentation comment, they will know about the default value and can apply that value. If we don't allow optional values as parameter, we don't need to apply default values in `***Designable`, for example, we don't need to apply default values in `configMask`, and we can apply all default values in `init(string: String?)` of the enum. For example, in `MaskType.init(string: String?)`, we can have something like 

``` Swift
switch name.lowercased() {
    case "circle":
      self = .circle
    case "polygon":
      self = .polygon(sides: Int(params[safe:0] ?? "6"))
    case "star":
      self = .star(points: Int(params[safe:0] ?? "5"))
    case "triangle":
      self = .triangle
    case "wave":
      self = .wave(direction: WaveDirection(rawValue:(params[safe:0] ?? "up").lowercased()), width: Float(params[safe:1] ?? "40"), offset:Float(params[safe:2] ?? "0"))
    case "parallelogram":
      self = .parallelogram(angle: Double(params[safe:0] ?? "60"))
    default:
      self = .none
    }
```

Just try to encapsulate the logic inside the enum. How do you think @lastMove @tbaranes ?

**Comment by lastMove** [comment]
I made a commit yesterday, [in the spirit of what @tbaranes suggested](https://github.com/JakeLin/IBAnimatable/commit/52cb8f5236cb3cf0e1b5ec5198ede20ca35ef92b)

Also I introduced `slideFade` which is actually the equivalent of the old `fade`
The new `fade` is just for non-sliding fade animations (fade /in/out/inout/outin)

It's another breaking change but I found it clearer.
How do you think about it ? 

It's ok for me to make enum parameters non-optional.
It will simplify the code.
one little detail about your sample. Since rawValue initialiser is failable 

``` swift
    case "wave":
self = .wave(direction: WaveDirection(rawValue:(params[safe:0] ?? "up").lowercased()), width: Float(params[safe:1] ?? "40"), offset:Float(params[safe:2] ?? "0"))
```

would become 

``` swift
    case "wave":
self = .wave(direction: WaveDirection(rawValue:(params[safe:0] ?? "").lowercased()) ?? .up, width: Float(params[safe:1] ?? "40"), offset:Float(params[safe:2] ?? "0"))
```

we could add an extension to have something like that 

``` swift
    case "wave":
self = .wave(direction: WaveDirection(rawValue: params[safe:0], default: .up).lowercased()), width: Float(params[safe:1] ?? "40"), offset:Float(params[safe:2] ?? "0") )
```

**Comment by JakeLin** [comment]
@lastMove thanks, I think we should use `slideFade` instead of `fade` because `slideFade` is more precise for the animations.

`self = .wave(direction: WaveDirection(rawValue: params[safe:0], default: .up).lowercased()), width: Float(params[safe:1] ?? "40"), offset:Float(params[safe:2] ?? "0") )` is better 👍

**Comment by lastMove** [comment]
Hi all, 
I think we can remove `BlurEffectStyle` and just make UIBlurEffectStyle conforms to IBEnum. What do you think about it ?

**Comment by JakeLin** [comment]
@lastMove perfect idea ✌

**Comment by lastMove** [comment]
Hi I have worked on `BlurEffectStyle` It seems working. 
Since I am updating those enums I need to be able to easily test them. 
So I could improve existing demo (playground part of the app) by the way.

What about having for BlurEffects a similar system than Animations one ? 
(A picker view with 2 components, one for `blurEffect` and the second one for `vibrancyEffect`).
We could also apply this logic to Masks, to be able to change instantaneously the polygon sides number, or the star points etc.

**Comment by tbaranes** [comment]
That would be nice. It's easier to use, and give a quick result when testing IBAnimatable 👍

**Comment by JakeLin** [comment]
I like the idea, I like the animations demo very much. Well done 👍👍👍we have two ViewControllers in the demo app for testing blurEffect, please have a look , there is a layout issue for vibrancy effect view because we need to change the view hierarchy for that effect. I haven't found a way to fix it. Have created an issue for it.

**Comment by lastMove** [comment]
Hi guys,
I wasn't available these days. I will advance on this issue this WE :)

**Comment by JakeLin** [comment]
@lastMove no worries, I am working on adding release 2.7 to swift3 branch. There are so many conflicts 😔

**Comment by JakeLin** [comment]
Finally, well-done guys @lastMove @tbaranes  🎉 🎉 🎉
