### ISSUE TITLE
Custom activity indicator

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#246]
We already talked about sliders, pickers, progressView, ... but here a new one: activity indicator. As the others, it will be mainly drive by a designable `activityIndicatorType`.

Plus the type, their will be some features straight forward:
- Loader color
- Background color / blur
- Blocking user interaction or not
- Start / stop animations
- hideWhenStopped
- ...

Just a though: I think the protocol should be conformed only by one animatable subview:`AnimatableActivityIndicatorView` (if possible with a shorter name). It won't make sense to have `AnimatableView` conforming to this protocol.

What do you think? Will it fit in IBAnimatable? 

If everyone agree with feature, the first library that I want to port is [NVActivityIndicatorView](https://github.com/ninjaprox/NVActivityIndicatorView).

**Comment by JakeLin** [comment]
I like the effects in NVActivityIndicatorView. It doesn't need any assets too. Since we are going to have an IBAnimatable plug-in system. We need to draw a line for core elements or plug-in elements. I like to ask all collaborators to decide. We can vote using reactions 👍. 

One of my ideas is if we are going to extend UIKit elements, it should be in Core. e.g. `UIActivityIndicatorView` and `UIPresentationController`. Otherwise, we may put it in a plug-in system. e.g. Material Design elements, Font Awsome elements.  But I am happy and open to let all of us decide which one belongs which.

**Comment by tbaranes** [comment]
I agree with you, every `UIKit` related should be in the core, and the others are in plugins.

**Comment by TheDarkCode** [comment]
Here's another repo for inspiration: https://github.com/lukagabric/LASIImageView

**Comment by tbaranes** [comment]
@TheDarkCode That is more a custom progress (#230) than an activity indicator, don't you think?

**Comment by TheDarkCode** [comment]
My thoughts were not so much restrictive to a numerical or overall status indication. It was the thought of a custom animated text component to the view that might have optional looping and potentially even sound and custom font attributes. Imagine it having an advertisement or some other call to action. Sort of like when you have the sentence or two on a video game load screen. 

Might be interesting to think super general. Maybe even do sound effects with linking to animation completion handlers on all animatables.

**Comment by JakeLin** [comment]
I think https://github.com/lukagabric/LASIImageView is more for an image downloader. It uses https://github.com/pokeb/asi-http-request 😱. Some libraries are doing this now like https://github.com/onevcat/Kingfisher and https://github.com/rs/SDWebImage. They require more programmatical APIs than Interface Builder settings.
