### ISSUE TITLE
Subclass of AnimatableView rendering problem in IB Preview window

### ISSUE THREAD

**Issue by DanielAsher** [IBAnimatable/IBAnimatable#262]
Hi,
thanks for a great framework!

I have attempted to use a custom subclass of `AnimatableView` in Interface Builder, but noticed that the view does not correctly render in the Preview window. 

I've created a branch on my fork that demonstrates the issue: [animationview-subclass-rendering-in-ibpreview](https://github.com/DanielAsher/IBAnimatable/tree/bugexpression/animationview-subclass-rendering-in-ibpreview).

`class CustomAnimatableImageView : AnimatableImageView { }`

In the example I've used `AnimatableImageView`, but I believe this behavior is true of `AnimatableView` and more generally.

Notice in the image below that the `Logo image view` `fillColor` is not being correctly rendered in the right-most preview window. Is this expected behavior?

Please let me know if I'm using the framework incorrectly.

Many thanks,

Daniel

![image](https://cloud.githubusercontent.com/assets/7915553/17305365/0a8c44f4-5822-11e6-8505-8b27d79a377e.png)

**Comment by tbaranes** [comment]
You are right, that's not the result expected. Your image should have a black background color since you set the `fillColor`.
The issue is in you `CustomAnimatableImageView`, if you want it to be designable in the interface builder, you have to tell him by adding `@IBDesignable` before the declaration:

``` swift
@IBDesignable class CustomAnimatableImageView : AnimatableImageView
```

Once that added, your image will be as expected.
Another thing, in the current state, your demo app won't compile, you have to add `import IBAnimatable` in your `CustomAnimatableImageView`.

 Let me know if you have more questions.
Thanks @JakeLin who points out the issue 😬

**Comment by DanielAsher** [comment]
@tbaranes @JakeLin thanks for spotting this oversight. Looks like it's working very nicely now!
