### ISSUE TITLE
Broken transitions

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#324]
Here a full list of the broken transitions:
- [ ] Fold
- [ ] Explode
- [ ] Turn
- [ ] Flip

**Comment by tbaranes** [comment]
Duplicate of #305

**Comment by JakeLin** [comment]
@tbaranes looks like they are different issues. Those transitions are broken when we build the library using Xcode 8. There are no problems when we build it using Xcode 7.  And #305, there is an exiting issue when we set the navigation bar to not translucent even using Xcode 7. But both issues are caused by the transition animators, either we implemented them wrongly, or Apple changed the behaviour for some API from Xcode 8.

**Comment by tbaranes** [comment]
The issue doesn't seem to be related with Xcode 8, they are working as expected on the iPhone 6 simulator. They are just broken on the iPhone 7.

**Comment by JakeLin** [comment]
@tbaranes you are 100% right, it is so weired it is working on iPhone 6 (iOS 10) but not iPhone 7 simulator 😱

**Comment by tbaranes** [comment]
Something interesting would be to test with a real device, maybe it's just a simulator bug?

**Comment by JakeLin** [comment]
Hopefully there is a simulator bug and Apple fixes it soon, I don't have iPhone 7 in hand yet, haven't got chance to test it 😞
