### ISSUE TITLE
Corner radius don't apply into AnimatableButton

### ISSUE THREAD

**Issue by nttra83** [IBAnimatable/IBAnimatable#375]
Hello,
I set a background image for this button. I wanna set corner radius for button but It don't work.
Could you help me fix this issue?
Thanks,

![screen shot 2016-12-16 at 12 04 02 pm](https://cloud.githubusercontent.com/assets/24289191/21252247/e38ada24-c387-11e6-9ddd-05f8796273a7.png)
![screen shot 2016-12-16 at 12 01 26 pm](https://cloud.githubusercontent.com/assets/24289191/21252248/e56a11ca-c387-11e6-9467-fe4d6e003aab.png)
![screen shot 2016-12-16 at 12 01 21 pm](https://cloud.githubusercontent.com/assets/24289191/21252249/e73be1e0-c387-11e6-847e-b32d4b28ad31.png)

**Comment by JakeLin** [comment]
Hi @nttra83, thanks for reporting that. I believe it is fixed by @mmadjer and has been merged in master, can you use master and try out? If it is fixed, I will make a release asap. Thanks.

**Comment by JakeLin** [comment]
Hi @nttra83 , I have tried and found out you need to set **Clip to Bounds** to **true**
<img width="565" alt="screen shot 2016-12-18 at 10 29 32 pm" src="https://cloud.githubusercontent.com/assets/573856/21293201/54f1c610-c571-11e6-855e-51a9c600bad6.png">

When we use background image for `AnimatableButton`
<img width="487" alt="screen shot 2016-12-18 at 10 30 03 pm" src="https://cloud.githubusercontent.com/assets/573856/21293199/52434038-c571-11e6-8064-d251e02ce3ad.png">


Can you try and close the issue if it works? thanks.

**Comment by nttra83** [comment]
Hello JakeLin,
Thanks for your support :).
It's work perfect :). But I wanna set a shadow color for AnimatableButton. It don't work when I set a shadow color :(. Could you fix it?
Thanks,

![screen shot 2016-12-19 at 10 44 29 am](https://cloud.githubusercontent.com/assets/24289191/21300674/a3c9a1a6-c5d8-11e6-9096-d82e8d322ac5.png)

**Comment by mmadjer** [comment]
It is working for me using your shadow values and code of master.
Change the shadow color, i.e. to black and you should see the shadow rendering. Light Gray and these values are very hard to see on white background.

**Comment by JakeLin** [comment]
@mmadjer I think @nttra83 's issue is when we set the shadow e.g. shadow color, shadow radius, shadow opacity or shadow offset, then corner radius (in this case, 10) is ignored. Because he / she (sorry, I am not sure) uses the `backgroundImage` property of the `AnimatableButton` (actually is in `UIButton`). It requires setting **Clip to Bounds** to `true`. But Setting shadow will set it to be false like

```
fileprivate func commonSetup() {
    // Need to set `layer.masksToBounds` to `false`.
    // If `layer.masksToBounds == true` then shadow doesn't work any more.
    if layer.masksToBounds {
      layer.masksToBounds = false
    }
  }
``` 

Code  from https://github.com/IBAnimatable/IBAnimatable/blob/master/IBAnimatable/ShadowDesignable.swift#L111

This issue only occurs when we use `backgroundImage` for `UIButton`.

The way we can fix it is to use a mask for all corner radius even `if cornerSides == .AllSides`, I have a try and find out if we set `cornerSides` to `topRight,topLeft,bottomRight`. It works fine like below. I will try and see whether it is a quick fix.

<img width="596" alt="screen shot 2016-12-19 at 10 11 57 pm" src="https://cloud.githubusercontent.com/assets/573856/21310764/dc625f58-c637-11e6-8972-ba02d8aea908.png">

**Comment by mmadjer** [comment]
Ah, yes I see now.

**Comment by JakeLin** [comment]
I have tried to use `mask` for all corner radius. But found out an interesting issue.

If we comment out `if cornerSides == .AllSides` case like 
```
  public func configureCornerRadius() {
    if !cornerRadius.isNaN && cornerRadius > 0 {
//      if cornerSides == .AllSides {
//        layer.cornerRadius = cornerRadius
//      } else {
        layer.cornerRadius = 0.0

        // if a layer mask is specified, remove it
        layer.mask?.removeFromSuperlayer()

        layer.mask = cornerSidesLayer()
//      }
    }
  }
```

Then we can support `AnimatableButton` (`UIButton`) with `backgroundImage` for both `cornerRadius` and shadow
<img width="571" alt="screen shot 2016-12-19 at 11 23 04 pm" src="https://cloud.githubusercontent.com/assets/573856/21312717/e179166c-c641-11e6-98af-f1d44d01825c.png">


But the normal case, `AnimatableButton` (`UIButton`) **without** `backgroundImage` doesn't render correctly in Interface Builder anymore. The shadow is gone. But it is working fine in Simulator. Bug of Interface Builder? Don't know yet. 

<img width="548" alt="screen shot 2016-12-19 at 11 27 16 pm" src="https://cloud.githubusercontent.com/assets/573856/21312806/6461952c-c642-11e6-82dc-e2b6597a2f11.png">

Shadow is gone without setting the background image in IB.


![simulator screen shot dec 19 2016 11 28 12 pm](https://cloud.githubusercontent.com/assets/573856/21312830/85b84158-c642-11e6-9027-3058054bb09a.png)

But working fine in Simulator.

Maybe a bug of Interface Builder again 😱

**Comment by nttra83** [comment]
Hello,
I faced same issue above :). I hope you can fix it soon :). 
Thanks @mmadjer @JakeLin

**Comment by JakeLin** [comment]
I have found out the reason because we don't call `configureMaskShadow()` inside `cornerRadius` property.

We can fix it like 
```
  @IBInspectable open var cornerRadius: CGFloat = CGFloat.nan {
    didSet {
      configureCornerRadius()
      configureMaskShadow()
    }
  }

  open var cornerSides: CornerSides  = .AllSides {
    didSet {
      configureCornerRadius()
      configureMaskShadow()
    }
  }
```

I will do a fix when I have some spare time, I am still looking after two boys 🙈🙉🙊. Or you can give it a go. Apply this change to all Elements e.g. `AnimatableButton`, `AnimatableView` and create a PR. Thanks.

**Comment by nttra83** [comment]
Hahaha, I also looking my son 👶 :).
I will try to fix it in my side.
Thank for your support :).

**Comment by mmadjer** [comment]
@JakeLin, will apply the proposed change.
