### ISSUE TITLE
MaskDesignable removes custom mask by default

### ISSUE THREAD

**Issue by DanielAsher** [IBAnimatable/IBAnimatable#406]
Hi,
thanks again for a great framework!
I require using a gradient mask on a subclass of AnimatableView. I didn't find a way to do this from the designer - so I created a `layer.mask` in my derived class. However, `MaskDesignable` removes the layer mask by default (i.e. when `.none`) in [this](https://github.com/IBAnimatable/IBAnimatable/blob/master/IBAnimatable/MaskDesignable.swift#L53) line.
I guess I'm still learning the philosophy of this library. I love being able to allow designers access to powerful features of UIKit, but - at first blush - this removes the ability to robustly use programmatic animation APIs.
best of wishes and all power to you!

**Comment by tbaranes** [comment]
Thanks for that report! It's true that the current implementation of `MaskDesignable` doesn't support any custom mask. It's a bit restrictive but we are in a complex context since we have to remove the mask if you choose to remove the mask later.

From what you are saying, I see three solutions:
- Use `GradientDesignable` directly to make your gradient. If it's not working let's debug it to make it compatible with `MaskDesignable` 😬 (Can't test it right now)
- Add a `custom` option to `MaskType` which will prevent removing a mask that is not implemented  by IBAnimatable. That could be a nice feature to have if it's been well thought. 
- Make your own `AnimatableView` to conform only designable protocols that you need.

Don't hesitate to make a PR if you decide to go with option 1 or 2!

About the philosophy ans implementation of the framework: it has been fully built using protocols in order to make the most flexible possible. All the Animatable* classes are just some wrappers of these protocols to make it easier to use. It's true that it has been more thought for the interface builder than programmatically usage but, I think, the usage should be working as expected for both. If that's not case, it's definitely an issue! Don't hesitate to open another issue or PR if you have any suggestions to improve it.

Hope that helps :)

**Comment by DanielAsher** [comment]
@tbaranes thanks for your super-quick responses.
I certainly agree about the complexity of the context! I also had similar ideas to all three of your suggestions. To your points in order:
* This doesn't seem orthogonal as a designer may require a fill gradient as well as a mask gradient
* Perhaps a `gradient` option to `MaskType` would handle this scenario, though full details of the mask gradient could clutter the IB property inspector. A simpler alternative to fix the issue would be a flag that tracks whether `MaskType` has be set to anything other than `.none` before removing the layer mask. 
* a `BasicAnimatableView` which factored out only those properties that don't interfere with programmatic APIs could be interesting. But in this case the question becomes would orthogonality require a `BasicAnimatableButton` etc.

More thinking required 🤔

**Comment by tbaranes** [comment]
About the option 1, I give it a try, and it's already working:

<img width="161" alt="screen shot 2017-02-26 at 18 45 27" src="https://cloud.githubusercontent.com/assets/1402212/23342066/c0d6f0bc-fc53-11e6-8b32-8a5bc10e659b.png">

When I said "GradientDesignable" I'm talking about the `startPoint`, `endPoint`, ... that you can find in the interface builder (or programatically).  `GradientDesignable` is supported by most of the Animatable* classes. Isn't it what you are looking for? Well, it's true that suppose you are not using a custom mask.

Anyway that doesn't solve the other question: how to handle custom masks? 

Personally, I won't be in favor of option 3 since it's bring a lot of work / maintenance, and easy misunderstanding for users. If the developer really a `BasicAnimatableView`... it will be for the best that he makes it himself.

I like option 2 (at least the idea), but since it will be a developer feature (I'm not expecting a designer to make its own masks since it involves code), I will be more in favor of an  usage which won't appear in the interface builder, that's why I was suggesting a dedicated type.

**Comment by DanielAsher** [comment]
I don't believe a gradient mask necessarily requires any code. It's simply a gradient with two colours (.clear and .black suffice), that smoothly shows/hides it's containing view. An image view with a radial gradient mask allows for an otherwise square image to have beautifully graduated circular border. 
A gradient mask on a blurred copy of the image allows for a natural focus effect.

As for the simpler fix - I feel the default behaviour should be not to intefere with custom drawing, so `.custom` should become the default and `.none` would represent the desire to remove any custom drawing.

Just my two cents :)

**Comment by DanielAsher** [comment]
I should say I'm not a public library designer, understand I have no experience in providing a stable API and very much defer to you in this matter!

**Comment by tbaranes** [comment]
I'm not sure to understand what gradient are you looking to do. I mean, what is missing to `GradientDesignable` to fulfill your goal? That protocol already makes gradient creation available in interface builder, and usable like the others protocol (either with Animatable* or your own classes by conforming to the protocol).

Agree with you to say it would be for the best to make `.custom` by default, one thing we have to keep in mind is that `.custom` have to remove the previous mask in some cases, for example: set a mask in interface builder then remove it (back to default which is custom) the mask shouldn't be drawn even if is custom is set.
What do you think about this @JakeLin ? Is that solution seems reliable to you?

**Comment by DanielAsher** [comment]
The gradient defined in `GradientDesignable` would need to be applied to the `layer.mask`, for which there is no mechanism at the moment. Then the designer would not be able to use this as an ordinary (fill) gradient.

Also `GradientDesignable` is over-featured for a gradient mask. Colours are unused in a gradient mask. I think the correct way to do this would be a `GradientMaskDesignable` with a `MaskDesignable` `MaskType` value of `.gradient` that knows how to apply it. Ideally `GradientMaskDesignable` would support radial gradients.

I understand this a fairly chunky feature request ☺️

**Comment by DanielAsher** [comment]
There may be a confusion here. A gradient mask is not a fill gradient on masked layer. It is a `CAGradientLayer` that is assigned to `layer.mask`

Apologies if this is still unclear.

**Comment by DanielAsher** [comment]
As to the issue of removing previous `layer.mask`, would a `previousMaskType : MaskType?` Be enough to know whether the `layer.mask` needs to be removed before being set?

**Comment by DanielAsher** [comment]
I'll try to sketch some code and either post or PR early next week 😇

**Comment by tbaranes** [comment]
I think I got the nuance now, thanks for the explanation! I don't know well enough this API to have a good opinion on the implementation. I will try to look at it or... wait for your PR 😜

I was thinking about a `previousMaskType` too, it should be enough to handle that case.

Looking forward! Thanks for bringing these discutions to us, it's great to make `IBAninatable` even better altogether 😊

**Comment by tbaranes** [comment]
Night thought: if we go with a `previousMaskType`, then I think we can apply the "don't remove custom mask" directly to `.none` instead of creating a new type!

Up to you 🤓

**Comment by DanielAsher** [comment]
@tbaranes that's certainly the simplest fix and has no repercussions on API clients. I would recommend this approach.

**Comment by tbaranes** [comment]
@DanielAsher I'm closing this now, but if you think that a `GradientMask` could be useful for `MaskDesignable`, don't hesitate to open a new issue to track that!
