### ISSUE TITLE
Present Modal custom size is not working 

### ISSUE THREAD

**Issue by kodekarim** [IBAnimatable/IBAnimatable#413]
Present Modal Custom Size is not working as it should be, the other parameters are working good like the corner radius , blur , animation type etc but the custom modal size is not working

the following view is the result modal width and height is 300 X 450 yet the result is as the image
![img_1973](https://cloud.githubusercontent.com/assets/13949425/23694274/e5b5c78e-03fe-11e7-8d54-d501470e9ede.PNG)

**Comment by tbaranes** [comment]
I just tried, it seems to be working as expected, I updated the example app the possibility to use a custom size (#414)

So for your case, we will need more input of how are you using it to be able to reproduce it. Can you give us any details that can help us to reproduce your issue?

**Comment by kodekarim** [comment]
on one view controller with a button action, i am presenting the view which is a subclass of AnimatableModalViewController and this is how my xcode attribute inspector of my popup view

plz correct me if I am doing wrong

<img width="240" alt="screen shot 2017-03-08 at 2 41 53 pm" src="https://cloud.githubusercontent.com/assets/13949425/23697336/6b4d24f6-040d-11e7-8f65-9666656b7b27.png">

**Comment by tbaranes** [comment]
In order to use `ModalSize.custom` you have to specify the custom keyword in the field, so instead of `300` and `400`, can you try to put in `custom(300)` and `custom(400)`? That's should solve your issue.

I think we can improve the size customisation by accepting directly numbers as you did, but have to check first if that's possible or no in the current implementation.

Let me know if that's solve!

**Comment by kodekarim** [comment]
@tbaranes  hey its working thanks
