### ISSUE TITLE
Strong reference cycle should be avoided

### ISSUE THREAD

**Issue by quanguyen** [IBAnimatable/IBAnimatable#468]
Hi Jake,

Thanks for this great lib. I really love it.

By the way, I often see you directly access `self` in closure, which could cause the strong reference cycle. Is there a reason when you use it?

For e.g.: In file `AnimatablePresentationController.swift`, line 190:

```
coordinator.animate(alongsideTransition: { _ in
        self.dimmingView.alpha = 1.0
      }, completion: nil)

```

which should be: 

```
coordinator.animate(alongsideTransition: { [weak self] (_) in
       guard let strongSelf = self else { return }
        strongSelf.dimmingView.alpha = 1.0
      }, completion: nil)
```

Do you agree?

**Comment by JakeLin** [comment]
@quanguyen Thanks for reporting this issue. I scan the code in the project, most of them should be fine because most of them are used within class methods like `UIView.animate()`. But there are some potential issues like what you found:

- [ ] AnimatablePresentationController e.g. within `coordinator.animate` - two places
- [ ] FlipAnimator e.g. `animateFlipTransition`
- [ ] PresentingViewController e.g. `hidePicker`
- [ ] AnimationsViewController e.g. `animatableView.animate`

If you have time, would you like to help us to fix them? thanks.

**Comment by quanguyen** [comment]
Ok, no problem. I'd just like to report so you could improve this great library in the next release.
