### ISSUE TITLE
Is there a way make percent-driven animations?

### ISSUE THREAD

**Issue by GoldenJoe** [IBAnimatable/IBAnimatable#496]
When making interactive controller transitions, it's important to be able to interrupt and "scrub through" animations. It's not clear how to do this in the sample app, or if it's even possible.

Can this be interrupted? Can you set its progress manually?
mysubview.animate(.flip(along: .x))

**Comment by JakeLin** [comment]
Yes, it's possible to use precent driven transition, use the animators via transition delegate , because IBAnimatable just extends UIKit. We can use those animators as the normal UIKit way. please have a look at https://www.raywenderlich.com/146692/ios-animation-tutorial-custom-view-controller-presentation-transitions-2

**Comment by GoldenJoe** [comment]
Awesome. Thanks!
