### ISSUE TITLE
Antialiasing on borders when using mask or cornerRadius

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#503]
Didn't find a solution yet, we may have to find a another way to draw our borders

**Comment by JakeLin** [comment]
![screen shot 2017-06-23 at 1 21 31 pm](https://user-images.githubusercontent.com/573856/27465454-f74f8860-5816-11e7-9efb-26f4a780f0a6.png)

I don't see this problem and I am using the latest release version of IBAnimatable with a UIView (width: 240, height: 128, borderWidth: 10, maskType: .circle)

**Comment by tbaranes** [comment]
Even when you run the app? I don't have it too in interface builder, only at runtime

**Comment by JakeLin** [comment]
![simulator screen shot 27 jun 2017 10 37 08 am](https://user-images.githubusercontent.com/573856/27565909-b073e6dc-5b24-11e7-8512-5d292fdd120c.png)

It looks alright for me too when I run it on the simulator Xcode Version 8.2.1 (8C1002) & Simulator iOS 10 iPhone 7.

**Comment by tbaranes** [comment]
Ok, after a few tests directly in IBAnimatable, I've been able to reproduce it on iPad 2 and iPhone 6 simulators. I think it's 100% reproductible, but it will be visible only with a few colours (limitation of the eye? CALayer bug?). In my case, when setting a white background colour to the main view it was not visible, whereas with a dark background it was reproductible. I pushed `hotfix/border_aliasing`, you can directly run the project, you'll get the following render:

![screen shot 2017-06-27 at 08 47 44](https://user-images.githubusercontent.com/1402212/27574118-5131d6de-5b15-11e7-83c1-56cbace34803.png)

**Comment by SD10** [comment]
I was looking into this but have to put it on the backburner for the moment. I just wanted to provide some context for record keeping.

The color bleeding through is the main views layer. The reason this is happening is due to the behavior of the `borderWidth` property of `CALayer`. 

From Apple [documentation](https://developer.apple.com/documentation/quartzcore/calayer/1410917-borderwidth): 
```swift
var borderWidth: CGFloat { get set }
```
> It is composited above the receiver’s contents and sublayers and includes the effects of the 
cornerRadius property.

The way to solve this is to not rely on this property if the `layer.cornerRadius` > 0. If there is a corner radius applied we will probably have to provide a custom `CALayer` to achieve the border.
