### ISSUE TITLE
Radial gradient

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#508]
Would be great to support both gradient type: Linear AND Radial

**Comment by JakeLin** [comment]
Good idea. `CAGradientLayer` on iOS doesn't support radial gradient, we need to draw it using `CGContextDrawRadialGradient` by ourselves.

**Comment by phimage** [comment]
![screen shot 2017-10-22 at 22 19 49](https://user-images.githubusercontent.com/8875768/31865912-2a814218-b777-11e7-8539-8b05026387e7.png)

Just some test by using a new `CALayer` class instead of `CAGradientLayer`
_Maybe an enum like `GradientMode` with `linear` or `radial` must created to select the good layer_

```swift
class RadialGradientLayer: CALayer {
  
  var startPoint:CGPoint = .zero
  var endPoint:CGPoint = .zero
  var colors: [CGColor] = [UIColor.clear.cgColor, UIColor.clear.cgColor]
  override init(){
    super.init()
    needsDisplayOnBoundsChange = true
  }
  required init(coder aDecoder: NSCoder) {
    super.init()
  }
  
  override func draw(in ctx: CGContext) {
    ctx.saveGState()
    let colorSpace = CGColorSpaceCreateDeviceRGB()
    let gradient = CGGradient(colorsSpace: colorSpace, colors: colors as CFArray, locations: [0.0,1.0])!
    let size = self.frame.size
    let radius = max(max(size.width - endPoint.x, endPoint.x), max(size.height - endPoint.y, endPoint.y))
    ctx.drawRadialGradient(gradient, startCenter: startPoint, startRadius: 0, endCenter: endPoint, endRadius: radius, options: CGGradientDrawingOptions.drawsAfterEndLocation)
  }
```
all the startPoint, endPoint etc... must be scale to the view frame.
