### ISSUE TITLE
Interactive Presentation (Question)

### ISSUE THREAD

**Issue by serjooo** [IBAnimatable/IBAnimatable#523]
First of all would like to thank everyone who is contributing to this great open source project! It is a very handy one!

I was playing around with the interactive dismiss and all the presentations; however, was wondering what if I want to add an interactive presentation to another view controller while pushing/presenting. How would I go about it yet keeping the AnimatedViewControllers or AnimatedNavigationControllers transition animation type and interactive dismiss gesture?

Thank you for your time, much appreciated.

**Comment by JakeLin** [comment]
@serjooo currently, we already add some interaction to dismiss and pop. To use interactive presentation for push / present. We can use the components in `IBAnimatable` like the other normal UIKit components. The goal of `IBAnimatable` is to extend UIKit not rewrite or replace it. For example, `PortalAnimator` conforms to `AnimatedTransitioning`, they are the transition animators. And interactive animator like `PanInteractiveAnimator`, they cover most of the normal gestures. They conform to `UIPercentDrivenInteractiveTransition`. You can use them in the normal UIKit way. Please have a look at how to do interactive transition in UIKit https://www.raywenderlich.com/170144/custom-uiviewcontroller-transitions-getting-started . Bear in mind, the document is a little updated. Please have a look Apple's doc too https://developer.apple.com/documentation/uikit/uipercentdriveninteractivetransition and https://developer.apple.com/documentation/uikit/uiviewcontrolleranimatedtransitioning. You can refer to the code in `IBAnimatable` as the example to write interactive transition. Let me know if you have any questions, thanks.

**Comment by gkye** [comment]
> How would I go about it yet keeping the AnimatedViewControllers or AnimatedNavigationControllers transition animation type and interactive dismiss gesture?

It seems all `UINavigationController`'s transitions are overriden once a `UIViewController` sets its `UIViewControllerAnimatedTransitioning` and from what I understand it seems the only way to have a custom transition while using `pushViewController` is to override these values. (All `UIViewController`s of your navigation controller will take on these transitions unless overridden again)
 I was faced with this issue a couple weeks back and decided the best solution until I find a better one would be to use `UIViewControllerTransitioningDelegate` and `present` instead of `pushViewController` (which did cause minor design issues) to avoid overriding and resetting the `UINavigationController`'s transitions back each time a custom transition was performed. 

Please post any solutions you come up with here 😄 


#### UINavigationControllerDelegate 
```swift
class ViewController: UIViewController, UINavigationControllerDelegate {
  // This will override the viewcontroller's navigation controller
  func navigationController(_ navigationController: UINavigationController, animationControllerFor operation: UINavigationControllerOperation, from fromVC: UIViewController, to toVC: UIViewController) -> UIViewControllerAnimatedTransitioning? 
  // interactive transition
  func navigationController(_ navigationController: UINavigationController, interactionControllerFor animationController: UIViewControllerAnimatedTransitioning) -> UIViewControllerInteractiveTransitioning? 
}
```
A better example can be found here https://github.com/IBAnimatable/IBAnimatable/blob/master/Sources/Animators/Common/Navigator.swift#L46


### Transition Delegate
```swift
  @IBAction func presentWithCustom(){
    let vc = CardsTransitionViewController()
    vc.transitioningDelegate = self
    present(vc, animated: true)
  }
  
  func animationController(forPresented presented: UIViewController, presenting: UIViewController, source: UIViewController) -> UIViewControllerAnimatedTransitioning?

  func animationController(forDismissed dismissed: UIViewController) -> UIViewControllerAnimatedTransitioning? 
```

**Comment by serjooo** [comment]
@JakeLin Thanks for the informative feedback. I did notice the interactive dismiss, and pop played around with it, checked out the code. Then I noticed an Enum `PresentationOperation` with the cases of `presentation, dismissal`. Saw that presentation was never used in any of the other classes, only the dismissal, thus guessing the interactive presentation was never implemented. 

I did attempt at implementing my own `UIPercentDrivenInteractiveTransition` but implementing the delegate myself with override all the implemented Transitions with IBAnimatable. Thus I thought maybe the right way would be through implementing it with IBAnimatable classes directly, so was wondering if this case was brought up before, because I checked the issues, didn't see any similar question being asked.

Moreover, as @gkye mentioned there are a few issues while using an `AnimatableViewController` and then `presenting` an `AnimatableNavigationController` or vice versa where some of the transitions would get overriden. I want to make a sample project of some of the issues I found and share it, maybe we can work on fixing them. I'll try to do this as soon as I get some time on my hands.

**Comment by JakeLin** [comment]
@gkye If I understand that correctly, it is not an issue of `IBAnimatable`, This behaviour (only one transition effort for all transition within the same `UINavigationController`) is designed by UIKit. I remember we discussed that before when we implement `AnimatableNavigationController`. We keep this behaviour as UIkit. I think if we want to have different behaviour / transition effort, we can use `present` like @gkye said. And the presented VC may have a Nav bar to make it look similar to the presenting VC. 

@serjooo I didn't figure out a good way to support interactive transition for `present` and `push` in Interface Builder, that requires more customised steps. So we provide a bunch of animators (as I mentioned above) to be used in code. That's why by default, we provide convenient ways (configuring in IB) to support presentation, dismissal and pop. Feel free to post more thinking, code any evidence, when we have time, we can discuss more and fix them if there are any issues, thanks.

**Comment by serjooo** [comment]
@JakeLin Oh alright, I follow now! Thank you for explaining! I will try to get that sample project up and running as soon as I can. Also will try to tackle the interactive present while I'm at it! Again much appreciated for your time and efforts!

**Comment by JakeLin** [comment]
@serjooo cool, feel free to re-open or create another issue if you more thing want to discuss.
