### ISSUE TITLE
`timingFunction` not working for spring animations

### ISSUE THREAD

**Issue by tbaranes** [IBAnimatable/IBAnimatable#564]
All animations using `UIView.animate` doesn't apply the timing function factor. Is there a reason for that?

**Comment by phimage** [comment]
Some parameters are for spring, others for cubic animations

at the beginning I think timing function is for cubic only
but recently I have made a secret move by adding `viewAnimationCurveOption` to `AnimationConfiguration` - not all timing functions are supported, only the well known ones

If some cubic animation do not use a timing function, it is a mistake

**Comment by tbaranes** [comment]
Looking at the code for `zoom` animation, I can't see anything related to timing function. I understand that all of them won't be supported, but at least the basic ones?

**Comment by phimage** [comment]
zoom is spring and use `animateIn` 

and since my "secret" move, use `TimingFunctionType.viewAnimationCurveOption` in `configuration.options`

the basic one are : linear easeIn easeOut easeInOut (cf. UIViewAnimationOptions curveXXX  or UIViewAnimationCurve)

**Comment by tbaranes** [comment]
I'm not sure I get the conclusion, is it expected that`zoom` isn't supporting timing function? Even `linear`, `easeIn`... ?

**Comment by phimage** [comment]
I think that `zoom` support (linear easeIn easeOut easeInOut) now since I add `configuration.options` in `animateIn`
eb695c3ec7fe5e0c9f52c0e6ac732c041650cb6a Animatable.swift

but maybe this doesn't work. I do not verify with my eyes

then I think in demo app you cannot change select a timing function, because I show the timing function button only for cubic animation, but I can edit that and show only the 4 timing functions predefined for spring animation

**Comment by tbaranes** [comment]
Got it, I will update IBAnimatable tomorrow and will give it a try!

**Comment by phimage** [comment]
If it's works, I will make a PR on demo app (to close this issue)

**Comment by tbaranes** [comment]
Alright, I give it a try, but it doesn't seem to be working (tried with zoom)

**Comment by phimage** [comment]
here this old code use UIViewAnimationCurve, not UIViewAnimationOptions
https://medium.com/@RobertGummesson/a-look-at-uiview-animation-curves-part-1-191d9e6de0ab

So in debug I see that I set the option to UIView.animate

Maybe we need additional options
**.overrideInheritedCurve**, .overrideInheritedOptions, .overrideInheritedDuration


maybe do not work also if using velocity and/or damping

**Comment by phimage** [comment]
very strange api
using debugger

- .curveLinear = [.curveEaseInOut, .curveEaseIn, .curveEaseOut]	
- .curveEaseInOut = [.curveEaseInOut]
- curveEaseIn = [.curveEaseInOut, .curveEaseIn]	
- curveEaseOut = [.curveEaseInOut, .curveEaseOut]	

the code I test

```swift
extension AnimationConfiguration {

  /// Options for spring animation.
  var options: UIViewAnimationOptions {
    if let curveOption = timingFunction.viewAnimationCurveOption {
      return [
        .allowUserInteraction,
        curveOption,
        .overrideInheritedCurve,
        .overrideInheritedOptions,
        .overrideInheritedDuration]
    }
    return [.allowUserInteraction]
  }

}
```

**Comment by phimage** [comment]
I know why this doesn't work

curves in `UIViewAnimationOptions` do not work with 
`UIView.animate(withDuration:,  delay:, usingSpringWithDamping:,  initialSpringVelocity:, options:, animations:, completion`

because `damping` and `velocity` already describe the timing function (a spring one)

I could see effect of options using
`UIView.animate(withDuration:,  delay:, options:, animations:, completion`

---

I have updated the demo app to be compatible with spring animation. I will commit later

Then for the fix maybe we could call `UIView.animate(withDuration:,  delay:, options:, animations:, completion` when
- this a timing function defined (not `none`)
- and maybe some check on damping and velocity value (we could not check default value .nan because value is modified to 0.7)
