### ISSUE TITLE
Custom properties for enum value

### ISSUE THREAD

**Issue by JakeLin** [IBAnimatable/IBAnimatable#76]
TBD

Some discussions 
https://github.com/JakeLin/IBAnimatable/issues/8
https://github.com/JakeLin/IBAnimatable/pull/59

**Comment by tbaranes** [comment]
The current ideas suggested (which could be working) in order to make that thread going further:
1. `Wave(up,40,10)`: MaskType(param1,param2,param3)
2. More AnimatableView's children to add custom designable properties following the shape
3. Other suggestions?

I prefer the first solution, but it could be maybe too hard to use, or improving a bit the syntax to be a bit more swift: `Wave(direction:up,width:40,offset:10)` (still annoying since the syntax is really strict)

**Comment by tbaranes** [comment]
Another approach:

``` swift
public enum Mask {
    case Circle()
    case Star(branches: Int)
    case Wave(up: Bool, width: Int, offset: Int)
}

Mask.Circle()
Mask.Star(branches: 5)
Mask.Wave(up: true, width: 40, offset: 40)
```

I still missing a nice way to make this working with the interface builder, but I find this approach more swifty.

**Comment by JakeLin** [comment]
@tbaranes @lexrus came up similar ideas before to use Swiftified enum. But since IB doesn't support enum yet, it can't fix our problem.

I prefer option one, and it can at least move us forward. If we can support option one, we can subclass `AnimatableView` to support option two if needed. 

To get the benefit of Swiftified enum, we can have 

```
public enum Mask {
    case Circle()
    case Star(branches: Int)
    case Wave(up: Bool, width: Int, offset: Int)
}
```

in code then map the `String` value e.g. `Star(6)` to `Star(branches:6)` for IB. And fall back to default value `Star(branches:5)` if the user put it wrongly like `Star5`, `Star(12` or Star2)
